Importing the Dependnecies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

Data Collection and Analysis

In [4]:
# loading the data from csv file toa python datframe
parkinsons_data = pd.read_csv('/content/parkinsons.csv')

In [5]:
parkinsons_data.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [6]:
# getting the number of rows and colummnsabout he dataset
parkinsons_data.shape

(195, 24)

In [7]:
# getting more information about the datset
parkinsons_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [8]:
# checking for missing values in each column
parkinsons_data.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [9]:
# getting some statistical measures about the data
parkinsons_data.describe()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count   195.000000    195.000000    195.000000      195.000000   
mean    154.228641    197.104918    116.324631        0.006220   
std      41.390065     91.491548     43.521413        0.004848   
min      88.333000    102.145000     65.476000        0.001680   
25%     117.572000    134.862500     84.291000        0.003460   
50%     148.790000    175.829000    104.315000        0.004940   
75%     182.769000    224.205500    140.018500        0.007365   
max     260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  ...  Shimmer:DDA         NHR         HNR      status  \
count        195.000000  ...   195.000000  195.000000  195.000000  195.000000   
mean           0.282251  ...     0.046993    0.024847   21.885974    0.753846   
std            0.194877  ...     0.030459    0.040418    4.425764    0.431878   
min            0.085000  ...     0.013640    0.000650    8.441000    0.000000   
25%            0.148500  ...     0.024735    0.005925   19.198000    1.000000   
50%            0.221000  ...     0.038360    0.011660   22.085000    1.000000   
75%            0.350000  ...     0.060795    0.025640   25.075500    1.000000   
max            1.302000  ...     0.169420    0.314820   33.047000    1.000000   

             RPDE         DFA     spread1     spread2          D2         PPE  
count  195.000000  195.000000  195.000000  195.000000  195.000000  195.000000  
mean     0.498536    0.718099   -5.684397    0.226510    2.381826    0.206552  
std      0.103942    0.055336    1.090208    0.083406    0.382799    0.090119  
min      0.256570    0.574282   -7.964984    0.006274    1.423287    0.044539  
25%      0.421306    0.674758   -6.450096    0.174351    2.099125    0.137451  
50%      0.495954    0.722254   -5.720868    0.218885    2.361532    0.194052  
75%      0.587562    0.761881   -5.046192    0.279234    2.636456    0.252980  
max      0.685151    0.825288   -2.434031    0.450493    3.671155    0.527367  

[8 rows x 23 columns]

In [10]:
# distribution of target variables
parkinsons_data['status'].value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [11]:
# adding code to improve accuracy

from sklearn.utils import resample

#separating majority and minority classes
df_majority = parkinsons_data[parkinsons_data.status==1]
df_minority = parkinsons_data[parkinsons_data.status==0]

# upsample minority class
df_minority_upsampled = resample(df_minority,
                                  replace=True,
                                  n_samples=len(df_majority),
                                  random_state=42)

# combine majority class with upsampled minority class
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

# display new class counts
df_upsampled.status.value_counts()


status
1    147
0    147
Name: count, dtype: int64

In [13]:
# grouping the data based on the target variable
parkinsons_data = df_upsampled.drop(columns='name',axis=1)
parkinsons_data.groupby('status').mean()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
status                                                            
0        184.030769    225.522605    147.969578        0.003609   
1        145.180762    188.441463    106.893558        0.006989   

        MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
status                                                                   
0               0.000022  0.001810  0.001951    0.005430      0.018133   
1               0.000051  0.003757  0.003900    0.011273      0.033658   

        MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA       NHR        HNR  \
status                    ...                                               
0               0.167340  ...   0.01356     0.029575  0.009897  24.582531   
1               0.321204  ...   0.02760     0.053027  0.029211  20.974048   

            RPDE       DFA   spread1   spread2        D2       PPE  
status                                                              
0       0.440536  0.692245 -6.759856  0.155317  2.138231  0.121632  
1       0.516816  0.725408 -5.333420  0.248133  2.456058  0.233828  

[2 rows x 22 columns]

Data Preprocessing

Separating the features and target

In [15]:
X = parkinsons_data.drop(columns=['status'],axis=1)
y = parkinsons_data['status']

print(X)
print(y)

     MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
44       243.439       250.912       232.435         0.00210   
50       124.445       135.069       117.495         0.00431   
50       124.445       135.069       117.495         0.00431   
166      237.323       243.709       229.256         0.00303   
188      114.563       119.167        86.647         0.00327   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0            0.000070   0.00370   0.00554     0.01109       0.04374   
1            0.000080   0.00465   0.00696     0.01394       0.06134   
2            0.000

Splitting the data to training data and test data

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
print(X.shape,X_train.shape,X_test.shape)

(294, 22) (235, 22) (59, 22)


Data Standardization

In [18]:
scaler = StandardScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled)

[[ 0.72053322  1.99347155 -1.01628878 ...  0.07375014 -0.38234835
  -0.62406399]
 [ 0.73025168  0.01877962  1.26479876 ... -0.32630349 -0.48035582
  -1.26602346]
 [-0.995194    0.10347744 -0.5374603  ...  0.06571039 -0.43258056
   0.88812801]
 ...
 [-0.9231224  -0.83840665 -0.52371776 ...  0.02893382  0.7249798
  -0.07801483]
 [-0.98727681 -0.8828414  -0.39822456 ... -0.11233604 -0.68982602
   0.45847609]
 [-0.54912922 -0.11052152 -0.89540887 ... -1.33600673 -1.25832289
   0.4391605 ]]


In [19]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

# Define a list of classifiers
classifiers = [
    RandomForestClassifier(),
    AdaBoostClassifier(),
    GradientBoostingClassifier(),
    LogisticRegression(),
    SVC(),
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    GaussianNB(),
    XGBClassifier()
]

# Create a dictionary to store the results
results = {}

#create a dataframe to store the results
results_df = pd.DataFrame(columns=['Model', 'Accuracy', 'F1-Score', 'Precision', 'Recall'])

# Train and evaluate each classifier
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{clf_name} Accuracy: {accuracy}")

    # Classification report
    print(f"Classification Report for {clf_name}:")
    print(classification_report(y_test, y_pred))

    # Confusion matrix
    print(f"Confusion Matrix for {clf_name}:")
    print(confusion_matrix(y_test, y_pred))
    print("="*50)

    #calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, output_dict=True)
    f1_score = report['weighted avg']['f1-score']
    precision = report['weighted avg']['precision']
    recall = report['weighted avg']['recall']

    #append results to dataframe
    results_df = pd.concat([results_df, pd.DataFrame({'Model': [clf_name], 'Accuracy': [accuracy], 'F1-Score': [f1_score], 'Precision': [precision], 'Recall': [recall]})], ignore_index=True)

RandomForestClassifier Accuracy: 0.9491525423728814
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        27
           1       1.00      0.91      0.95        32

    accuracy                           0.95        59
   macro avg       0.95      0.95      0.95        59
weighted avg       0.95      0.95      0.95        59

Confusion Matrix for RandomForestClassifier:
[[27  0]
 [ 3 29]]


<ipython-input-19-fe7f93d7ea47>:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results_df = pd.concat([results_df, pd.DataFrame({'Model': [clf_name], 'Accuracy': [accuracy], 'F1-Score': [f1_score], 'Precision': [precision], 'Recall': [recall]})], ignore_index=True)
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier Accuracy: 0.9491525423728814
Classification Report for AdaBoostClassifier:
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        27
           1       1.00      0.91      0.95        32

    accuracy                           0.95        59
   macro avg       0.95      0.95      0.95        59
weighted avg       0.95      0.95      0.95        59

Confusion Matrix for AdaBoostClassifier:
[[27  0]
 [ 3 29]]
GradientBoostingClassifier Accuracy: 0.9661016949152542
Classification Report for GradientBoostingClassifier:
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.94      0.97        32

    accuracy                           0.97        59
   macro avg       0.97      0.97      0.97        59
weighted avg       0.97      0.97      0.97        59

Confusion Matrix for GradientBoostingClassifier:
[[27  0]
 [ 2 30]]
LogisticRegres

In [20]:
results_df

Model  Accuracy  F1-Score  Precision    Recall
0      RandomForestClassifier  0.949153  0.949240   0.954237  0.949153
1          AdaBoostClassifier  0.949153  0.949240   0.954237  0.949153
2  GradientBoostingClassifier  0.966102  0.966160   0.968440  0.966102
3          LogisticRegression  0.847458  0.845873   0.885593  0.847458
4                         SVC  0.864407  0.863469   0.895400  0.864407
5        KNeighborsClassifier  0.932203  0.932281   0.940951  0.932203
6      DecisionTreeClassifier  0.949153  0.949240   0.954237  0.949153
7                  GaussianNB  0.779661  0.775440   0.829659  0.779661
8               XGBClassifier  0.966102  0.966160   0.968440  0.966102

Model Training

Gradient Boosting Classifier

In [21]:
# use the model giving best accuracy

gb_model = GradientBoostingClassifier()
gb_model.fit(X_train_scaled,y_train)
y_pred = gb_model.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Classification report
print(f"Classification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print(f"Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9661016949152542
Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.94      0.97        32

    accuracy                           0.97        59
   macro avg       0.97      0.97      0.97        59
weighted avg       0.97      0.97      0.97        59

Confusion Matrix:
[[27  0]
 [ 2 30]]


Model Evaluation

Accuacy Score


In [22]:
# accuracy score on training data
X_train_prediction = gb_model.predict(X_train_scaled)
training_data_accuracy = accuracy_score(y_train,X_train_prediction)
print('Accuracy score of training data : ',training_data_accuracy)

Accuracy score of training data :  1.0


In [23]:
# accuracy score on test data
X_test_prediction = gb_model.predict(X_test_scaled)
test_data_accuracy = accuracy_score(y_test,X_test_prediction)
print('Accuracy score of test data : ',test_data_accuracy)

Accuracy score of test data :  0.9661016949152542


Saving the trained model

In [24]:
import pickle

filename = 'parkinsons_model.pkl'
pickle.dump(gb_model,open(filename,'wb'))

# laoding the saved model
loaded_model = pickle.load(open('parkinsons_model.pkl','rb'))

In [25]:
# Building a Predictive System
input_data = (116.67600,137.87100,111.36600,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.51700,0.02924,0.04005,0.03772,0.08771,0.01353,20.64400,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975)

# changing input data as numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardize the data
std_data = scaler.transform(input_data_reshaped)

prediction = gb_model.predict(std_data)
print(prediction)
if (prediction[0] == 0):
  print("The person does not have Parkinsons Disease")
else:
  print("The person has Parkinsons Disease")

[1]
The person has Parkinsons Disease


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
